# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.AnswerBase')),
                ('body', models.IntegerField(blank=True, null=True)),
            ],
            bases=('survey.answerbase',),
        ),
        migrations.AddField(
            model_name='response',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='response',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
