# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20161206_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Latitude'),
        ),
    ]
