# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_androidresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidResponseV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userEmail', models.CharField(max_length=255)),
                ('userContact', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.AndroidResponseV2')),
            ],
        ),
    ]
