# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_androidresponsev2_userquestionresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AndroidResponseV2',
            new_name='UserResponse',
        ),
    ]
