# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20161223_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userEmail', models.CharField(max_length=255)),
                ('userContact', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Longitude'),
        ),
    ]
